apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: sampleapp
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        metadata:
          labels:
              expect: succeeded
        spec:
          source:
            git:
              url: https://github.com/gevou/knative-blueprint.git
              revision: master
          template:
            name: buildpack
            arguments:
            - name: IMAGE
              value: &image us.gcr.io/knative-blueprint/sampleapp:latest
      revisionTemplate:
        spec:
          container:
            image: *image
            imagePullPolicy: Always